### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by s1104373** [geo-frontend/nlmaps#32]
I get an error trying to install the nlmaps package with NPM.

```
npm install --save @geo-frontend/nlmaps

> canvas@1.6.13 install D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas
> node-gyp rebuild


D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\kalkm\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node "C:\Users\kalkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Program Files\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kalkm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kalkm\AppData\Roaming\npm-cache\_logs\2018-11-29T13_58_46_952Z-debug.log
```

I can not find what is wrong. 

It looks like the error is python related. Is it possible that is can only install when using python 2.7

**Comment by s1104373** [comment]
Installing python 2.7 did the trick. Now getting a different error:

```
D:\Projects_school\KBSSE3\frontend>npm install --save @geo-frontend/nlmaps

> canvas@1.6.13 install D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas
> node-gyp rebuild


D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\kalkm\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node "C:\Users\kalkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) [D:\Projects_school\KBSSE3\fronten
d\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [D:\Projects_school\KBSSE3\
frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.cc) [D:\Projects_school\KBSSE3\frontend
\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\init.cc) [D:\Projects_school\KBSSE3\frontend\
node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [D:\Projects_school\KBSSE3
\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\ImageData.cc) [D:\Projects_school\KBSSE3\fron
tend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
  win_delay_load_hook.cc
d:\projects_school\kbsse3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\src\canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [D:\Projects_sch
ool\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kalkm\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kalkm\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects_school\KBSSE3\frontend\node_modules\@geo-frontend\nlmaps\node_modules\canvas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kalkm\AppData\Roaming\npm-cache\_logs\2018-11-29T14_19_26_163Z-debug.log

```
